### PR TITLE
Various updates

### PR DESCRIPTION
**Pull request by oerdnj**
It's better to look at the individual commits:

- the DNSSEC in the introduction is just confusing, TSIG doesn't have to be justified (or this stuff needs to go to Security Considerations
- I update the RDATA specification to have the format table and slightly better description
- Various other nits

### CODE REVIEW

**Comment by fxdupont** [comment]
Note the DNSSEC stuff and various nits are from RFC 2845 so we have to keep them. If there is a consensus to move DNSSEC stuff from the introduction to security considerations I shall do it.
I updated the .gitignore.
I believe too the artwork table is better for the RDATA format but I disagree about changing for instance u_int16_t into 2 octets.
Finally where is the u_int64_t? Perhaps you mean no u_intXX_t?

**Comment by fxdupont** [comment]
The DNSSEC stuff is from RFC 2845 so we have to keep it. Now if there is a consensus to move it to the Security Considerations I shall do it.
I adopted the .gitignore changes and the RDATA artwork.
About various nits I disagree to change for instance u_int16_t into 2 octets because a type is more than a value length. Now 2 octet long unsigned integer is a bit long so IMHO u_int16_t & co is a less bad solution.

**Comment by oerdnj** [comment]
> Note the DNSSEC stuff and various nits are from RFC 2845 so we have to keep them.

Why? We are updating the RFC, not making just an errata, so we can make all the changes that make sense.

**Comment by fxdupont** [comment]
We are doing a bit more than updating so I prefer to not remove material. Now moving it to a better place make sense.
Another point: I'll change the u_intXXX_t for the C standard uintXXX_t (even if uint48_t in fact does not exist). Or if you prefer I'll stand before that integer fields are unsigned so it will be enough to give the length.

**Pull request merged**
